name: MT7620云编译

on:
  workflow_dispatch:
    inputs:
      production:
        description: 设置固件型号(用空格分开)：
        default: "PSG1218"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 同步主存储库
      uses: actions/checkout@master
    - name: 初始环境设置
      run: |   
        sudo apt-get update && sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt install libtool-bin gperf python3-docutils autopoint gettext
    - name: 准备工具链
      run: |
        mkdir -p /opt/images && cd toolchain-mipsel && sh dl_toolchain.sh
    - name: 自定义
      run: |
        #cd trunk && sed -i "s/busybox_id=\"1.34.1\"/busybox_id=\"1.24.x\"/g" ./build_firmware_modify
        #cd user/busybox && sed -i "s/SRC_NAME=busybox.*/SRC_NAME=busybox-1.24.x/g" ./Makefile
        cwd=`pwd` && DIR=${cwd//\//\\\/}\\/toolchain-mipsel
        sed -i "s/^CONFIG_TOOLCHAIN_DIR=.*$/CONFIG_TOOLCHAIN_DIR=${DIR}/g" trunk/configs/templates/${{ github.event.inputs.production }}.config
    - name: 开始编译
      run: |
        cd trunk && sudo ./build_firmware_ci ${{ github.event.inputs.production }} 0
        mv -f images/*.trx /opt/images && sudo ./clear_tree_simple >/dev/null 2>&1
    - name: 上传到Artifacts
      uses: actions/upload-artifact@master
      with:
        name: Padavan-3.4
        path: /opt/images
