name: MT7621云编译

on:
  workflow_dispatch:
    inputs:
      production:
        description: 设置固件型号(用空格分开)：
        default: "K2P MSG1500-7615 NEWIFI3"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 同步主存储库
      uses: actions/checkout@v2.1.0
    - name: 初始环境设置
      run: |   
        sudo apt-get update && sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt install libtool-bin gperf python3-docutils autopoint gettext
    - name: 准备工具链
      run: |
        cd toolchain-mipsel && sh dl_toolchain.sh
    - name: 开始编译
      run: |
        cd trunk && for m in ${{ github.event.inputs.production }}; do fakeroot ./build_firmware_ci $m; ./clear_tree_simple >/dev/null 2>&1; done
    - name: 上传到Artifacts
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Padavan-3.4
        path: images
